### ISSUE TITLE
ViewSwitcher: Increase limit on minimal view mode

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#100]
List items in minimal need less vertical space by a lot in comparison to the others view modes. When switching a list view to minimal mode the additional up space is unused.

Increase (maybe double) the limit when switching to minimal view.

![Screen Shot 2020-05-27 at 15 59 39](https://user-images.githubusercontent.com/6977434/83029958-8eee9c80-a033-11ea-99ec-f1b1e6302d33.png)

**Comment by nilmerg** [comment]
I had recently the same in mind, but discarded it because when using a common resolution such as 1920x1080 the *free* space is negligible (to me). As shown in your screenshot. And it's not that switching the limit manually is difficult, is it? Anyway, I personally deemed it not necessary to change at a second glance. Just my2cents.

**Comment by flourish86** [comment]
It's not difficult, but taking the extra step is not just one click. It avoids mental overhead and distracting the user. Most users probably won't take the extra step and therefore not take full advantage of the minimal view.

The amount of free space on the screen shots only shows half of the problem. The rest of the list items would be scrollable and therefore prevent the user from having to use the pagination to get to the next page.

I think we already agreed on this and why not do it when it enhances the ux?

**Comment by nilmerg** [comment]
I think we talked about this already, but there's a technical issue which is far more serious than the *wasted* space. You already mentioned the pagination. That's there the problem is. Consider the following:

* A user is on page 20 with the default limit of 25 and the default view mode
* The user now chooses the minimal view mode which changes the limit to 50
* Page 20 now shows an entirely different set of results, unexpectedly
* The user should be on page 10 after the change

When increasing the limit based on the view mode, we have to re-calculate the pagination position. The view mode switcher will be a form with #182, that makes this *magic* now possible. Also, the limit must not change if it's not the default.
