### ISSUE TITLE
ViewSwitcher: View mode should be maintained, when switching views

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#103]
The list views fall back to default view mode, when switching views.

See

![Screen Recording 2020-06-10 at 11 32 14](https://user-images.githubusercontent.com/6977434/84251865-38db2800-ab0e-11ea-8d0d-f9713923c81b.gif)

The selected view mode should be maintained, though.

Every object list should have his view mode saved.

**Comment by nilmerg** [comment]
Then the widget is in the wrong place as well. Otherwise the limit, sort order and filters should also apply to all views.

For the the view switcher to maintain it's mode over different views it has to go to the sidebar or header, just like the future environment selection or such a thing. Also, if this gets implemented, it can't be a url parameter anymore. The urls in the sidebar are somewhat hardcoded and independently refreshed/assembled. (There are also custom items which may also be affected by the mode change) This then must be a *state* in javascript and we'll transmit a special request header for a new loaded view.

**Comment by flourish86** [comment]
Then the widget is in the wrong place as well. Otherwise the limit, sort order and filters should also apply to all views.

> For the the view switcher to maintain it's mode over different views it has to go to the sidebar or header, just like the future environment selection or such a thing.

Please, read exactly. The list view mode should just be maintained per list, not globally.

See
> Every object list should have his view mode saved.

> Also, if this gets implemented, it can't be a url parameter anymore. The urls in the sidebar are somewhat hardcoded and independently refreshed/assembled. (There are also custom items which may also be affected by the mode change) This then must be a state in javascript and we'll transmit a special request header for a new loaded view.

I don't think the user cares, how this is implemented technically, on the first hand. They would just not want to switch view mode again and again, do they?

**Comment by nilmerg** [comment]
> The list view mode should just be maintained per list, not globally.

I would not expect a widget, that's located at the same place as the limiter, to affect more than the current view. I'm not stating that this is bad idea, I'm just saying the widget is in the wrong place if it behaves as you suggest and keeps being displayed in the controls. Just see this as a comment, not criticism.

> I don't think the user cares

I didn't mention this with the user in mind, it's just a comment from the technical perspective how I see this implemented.
