### ISSUE TITLE
Detail view list items hover background cropped.

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#134]
## Describe the bug
The background of comment and downtime list items in detail views is cropped.

## Expected behavior
Something that results in the same as:

```
.host-detail .list-item {
  margin-left: -1em;
  margin-right: -1em;
  padding-left: 1em;
  padding-right: 1em;
}
```

## Screenshots
![Screenshot 2020-10-19 at 18 01 44](https://user-images.githubusercontent.com/6977434/96476730-e2a59080-1235-11eb-867f-596a8d2af6f6.png)

![Screenshot 2020-10-19 at 18 07 38](https://user-images.githubusercontent.com/6977434/96476790-fb15ab00-1235-11eb-8747-6f47d4f3c604.png)

**Comment by nilmerg** [comment]
I really struggled to understand what you mean at first. I didn't see any problem. Even on your screenshots everything looks fine. Then I applied the suggested CSS, and, yeah I now get it... But why? It's not `.full-width` content, unlike the big list on the left, why should these lists behave differently as the other content in the detail area? (Consistency doesn't apply here, because it's inconsistent either way.)

**Comment by flourish86** [comment]
Sorry, missed to answer your comment there, but this is still relevant.

I think we should value visual consistency over implementation details here. It also looks odd since the timestamp element doesn't have enough space to the edge of the list element.

A simple `margin: 0 -1em` for the list would fix this.

![Screen Shot 2021-08-23 at 14 48 13](https://user-images.githubusercontent.com/6977434/130450077-bdf89b86-3aa5-4d47-8345-e2ef8d253d4b.png)

You can see it also here for the active element.

![Screen Shot 2021-08-23 at 14 50 55](https://user-images.githubusercontent.com/6977434/130450246-9e85185c-67db-4944-9513-123fcffd3376.png)
