### ISSUE TITLE
Re add perfdata pie charts in list views

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingadb-web#160]
In the new lists the pie charts for the perfdata that used to be on the right side of some service list items moved to the detail view. See:

![image](https://user-images.githubusercontent.com/22217062/106453924-50469700-648a-11eb-8285-eecab1b6c8ac.png)

vs

![image](https://user-images.githubusercontent.com/22217062/106454119-94d23280-648a-11eb-91b7-6daee34f5443.png)

From feedback from the community I gathered, that those were very useful in the overview and comparatively unneccesary in the detail view :)

**Comment by flourish86** [comment]
### Pie Charts in detailed list items

Adding the pie charts in the detailled list view mode view would give it a little more value.

I wouldn't add back it to the default view mode, since I assume that not every user will need the information and for them it would be a distraction.

In the detaillied view mode an option would be to add an additional footer line, which could hold additional information (similar to the icons for downtime, etc. in the legacy monitoring module). This could also hold a reasonably limited amount of pie charts. The footer should only appear, when necessary.

Hovering them could of course reveal more data, like the label and some values.

### Limit the number of lines in detailed list items

We should also limit the number of max lines for the detailled list items. I'd suggest 5, which would eventually result in max. 7 lines, including the title/date, plugin output and footer (if applicable).

Here's a mockup.

![Artboard](https://user-images.githubusercontent.com/6977434/111666135-ba858200-8813-11eb-9e98-e4ca1b5dd91d.jpg)

**Comment by flourish86** [comment]
### Pie Charts in detail view
We also should resize the pie charts in the detail view properly and optimize the table styles.

* left align label and make them bold
* right align table cells with numbers (e.g. 145 GiB)
* Prevent number table-cells for wrapping
* maximize main column width (in the case label)
* ellipsisize main column where necessary

Something like this.
![Screen Shot 2021-03-18 at 17 25 28](https://user-images.githubusercontent.com/6977434/111661231-23b6c680-880f-11eb-8a4e-bb1ceb1a0808.png)
