### ISSUE TITLE
Featurewish: Add a noticesign in serviceoverview

### ISSUE THREAD

**Issue by x1tus** [Icinga/icingadb-web#23]
Hey there,

I wish there were a little notice sign in the serviceoverview like in icinga1. 
Instead to click on every check to look if there is a comment by someone would it be great if you can see the notification by a little sign at the service without clicking on it. For example at the same area like the acknowledgment.

**Comment by nilmerg** [comment]
Hi,

we decided against this previously and now again because simple comments are not considered important enough. The host/service lists shouldn't be cluttered by every single information about an entry. Only the really important details are there and that includes acknowledgements. An acknowledgement comment is important because it's linked to an acknowledgement which is removed at some time. A simple comment however may also be a note on what to do in case of a problem that's there nearly forever. Should this be visible on the list?

And why are you searching for hosts/services with a comment by someone? Is it the *someone* which interests you? If so, can't you just look at the list of comments and search for the author?

**Comment by nilmerg** [comment]
No feedback for six weeks. Closing.

**Comment by lippserd** [comment]
We could solve this properly with the following approach:

We introduce two new attributes `has_comment` and `has_problem_comment`.

`has_comment` is mainly used for filtering. It is set to `y` once a comment is added.

`has_problem_comment` on the other hand is reset after every recovery. If a comment is added for the current problem, it is set to `y`. This way we could have an indicator in the list views which actually has value. It could also be used for filtering of course.

@flourish86 @nilmerg What do you think?

**Comment by nilmerg** [comment]
Sure, if a schema change is an option for us to provide this, go ahead

**Comment by flourish86** [comment]
We should only put an indicator in the list items, if we are sure that is delivers value for most users.

I wouldn't put it into the state ball, solely because it is not saying anything about the status itself.
Also, I would try to prevent something like the icons in the current Icinga Web 2 list items, where every possible state is indicated by a separate icon - at least not in every view.

If really necessary, what do you think about a separate footer line in detailed view?

![Screenshot 2020-04-21 at 16 36 56](https://user-images.githubusercontent.com/6977434/79878937-52090780-83ee-11ea-904a-e6487a8910a3.png)

**Comment by nilmerg** [comment]
We have a footer in detailed view now. Let's show that there.

**Comment by nilmerg** [comment]
Nevermind, that's been introduced as part of #176
