### ISSUE TITLE
Show last host/service comment in a popup in detailed mode

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#231]
## Is your feature request related to a problem? Please describe.
Currently we only indicate in detailed list mode that a host or service has a comment. But who authored it and the comment itself is not shown.

## Describe the solution you'd like
Upon hovering over the comment icon in the list item's footer, a popup should open showing the comment's author and the comment's content.

## Additional context

* https://github.com/Icinga/icingadb-web/blob/master/library/Icingadb/Widget/ServiceListItemDetailed.php#L34-L37
* https://github.com/Icinga/icingadb-web/blob/master/library/Icingadb/Widget/HostListItemDetailed.php#L34-L37
* https://github.com/Icinga/icingadb/issues/317

**Comment by nilmerg** [comment]
Above I've added links showing the current way of indicating that a comment exists. This is far from ideal at the moment, as it runs a subquery for each item in the list. What I'd like to have instead, is that the last comment for each list entry is already fetched with the main database query.

For this you'll have to implement a new relation `last_comment` in the `HostState` and `ServiceState` models, which is joined by a `LEFT` join. This relation needs to be selected then as part of the main query, take a look at the `with()` call in the respective controller/index action for this.

The popup should be a *rich* popup. Not just a standard title. So it should be a box with the enlarged comment icon maybe and a border around it that points to the hovered icon with a directional indicator? You should probably first draw a mockup/picture of this before actually implementing it and show it @flourish86, or ask him to do that for you.

**Comment by flourish86** [comment]
Something like this.

Some notes:

* the popover should be a max. width, so that that lines won't get too long be read properly
* in this case it could contain the full list item in default view mode
* This would imply, that the comment content would be ellipsisized after two lines, which I think would be fine. It's a quick view, and nobody is going to want to read the lord of the rings trilogy in this context
* Make sure there's a hover effect for the comments icon in the list

![Desktop](https://user-images.githubusercontent.com/6977434/128883881-cbdd0733-9403-41e6-a2bb-dac681bc9ff5.jpg)
