### ISSUE TITLE
The visualization of the check statistics "now" time point is not correct 

### ISSUE THREAD

**Issue by mcktr** [Icinga/icingadb-web#38]
Hello,

I am currently testing IcingaDB in a local test environment. In the _Check Statistics_ section is a nice visualization of _Last Update_ and _Next Check_, both are indicated by blue dots. There is  also a dark grey dot that indicates the _Now_ time point. For my understanding the _Now_ time point should be between the two blue dots, unfortunately it is on the very left side. 

![Bildschirmfoto von 2020-03-21 17-08-11_shadow](https://user-images.githubusercontent.com/18580278/77230757-b5f1a380-6b96-11ea-9573-088de97c3482.png)

I tested Chromium Version 80.0.3987.132 and FireFox Version 68.6.0esr.

The systems run on:

- Debian 10 "buster"
- NGINX 1.14.2
- PHP 7.3
- MariaDB 10.3.22

The `timezone` parameter in the `php.ini` is correctly set to `Europe/Berlin`.

Thanks and best regards
Michael

**Comment by dmitriy-terzeman** [comment]
Having around the same issue with visualisation, server part installed on Centos7.7,
Client side: web browser Google Chrome 80.0.3987.149, Mac OS Catalina 10.15.3

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This may be a superfluous question but is the time of your servers synchronized?

Does this happen for all objects or just some?

Best regards,
Eric

**Comment by mcktr** [comment]
My testing server uses `ntp` to keep the time synchronized. This happens for all objects (hosts, services).

**Comment by nilmerg** [comment]
I'm a bit lost here. The dots are positioned using simple percent values. The value of the grey dot (*Now*) can't be lower than 10% which is exactly the same value the first blue dot gets (*Last Update*). Since the first blue dot is positioned correctly the 10% can't be the issue. The grey dot then must have a lower value nonetheless, is not positioned absolute or its given position is completely ignored. All three options shouldn't be possible, though. Sooo...

I've tried several things, used exactly the Chromium and FireFox (even the ESR one) versions mentioned. To no avail. Now I need your help, that involves opening the browsers devtools and taking a screenshot. :grin: 

Such as this: (Taken in Chromium)
![Bildschirmfoto von 2020-03-31 14-40-38](https://user-images.githubusercontent.com/16668527/78028176-e2f44200-735e-11ea-9561-45f0a6db9575.png)

To get there follow these steps:
* Right click the grey dot and choose "Inspect"
* In the devtools that pop up go to the "Computed" tab at the right
* Unfold the "left" and "position" instructions, still with the grey dot selected at the left

**Comment by mcktr** [comment]
Thanks for the detailed information on how to look deeper into this. :+1: 

![Bildschirmfoto von 2020-03-31 17-05-51_shadow](https://user-images.githubusercontent.com/18580278/78042213-007ed700-7372-11ea-9e1f-b15317ad7759.png)

I think I found the culprit. If you have a really close look at the position value you will notice that the value uses a comma `,` instead of a dot `.`. Changing this to a point it will instantly work.

![Bildschirmfoto von 2020-03-31 17-06-00_shadow](https://user-images.githubusercontent.com/18580278/78042561-72efb700-7372-11ea-9fb2-a45e20b9b90d.png)

I think the problem is somehow related to the localisation, if I explicitly set `en_US` as my language in the Icinga Web 2 profile settings this will also work.

**Comment by nilmerg** [comment]
Ouch. Yes, that's the issue here. Thanks for reporting back so quick.
