### ISSUE TITLE
CheckStatistics: Reflect disabled active checks

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#403]
## Describe the bug
Disabling active checks afftects the “next check” value from the check statistics widget. Currently this leads to negative values for the “next check” or when the view is updated wrong values

## To Reproduce
1. Open a service/host detail view
2. disabled active checks
3. Wait until the check interval is over to see the negative “Next Check” value

## Expected behavior
We should consider the Check Statistics widget to reflect that active checks are disabled.

## Screenshots
![Screen Shot 2021-10-20 at 13 55 45](https://user-images.githubusercontent.com/6977434/138087967-5b93d0b5-63f8-4747-bb7b-b19d4e1b9304.png)

**Comment by nilmerg** [comment]
## With passive checks on ...

it looks now this way: (The counter only goes negative until the next autorefresh runs, which is fine IMHO)

**Prior**
![Screenshot from 2022-07-18 10-55-46](https://user-images.githubusercontent.com/16668527/179477665-9cb4c64c-6945-4bd3-bd53-9e87a15bcf45.png)

**After**
![Screenshot from 2022-07-18 10-56-14](https://user-images.githubusercontent.com/16668527/179477709-5563549f-1939-49b2-ba90-bcf39c0d052e.png)

## With passive checks off ...

t works the same

**Prior**
![Screenshot from 2022-07-18 10-50-50](https://user-images.githubusercontent.com/16668527/179477819-0fc42ee8-a113-418a-bbd9-3ffb63a62e72.png)

**After**
![Screenshot from 2022-07-18 10-51-15](https://user-images.githubusercontent.com/16668527/179477831-b00f5741-a11e-4f40-b7fb-335178b84fd4.png)

## Conclusion

With passive checks on the view is fine since the next update timer doesn't run into negative values. (Unless the autorefresh is disabled..) And as long as passive checks are on, they might come in and there is no reason for indicating this "standard" behavior.

With passive checks off however, it behaves the same. As then no update is accepted (Unless someone clicks on `Check now`, which forces a check) the timer runs into it's next update and resets on and on. We should reflect *that* by suspending the `Now` cursor and by showing `not-scheduled` (visually similar to empty-state) in the next check bubble.

**Comment by flourish86** [comment]
This is how I the Widget should look, if active AND passive checks are disabled. We figured, that it wouldn’t make sense to vizualize that only one is disabled.
![Frame 41](https://github.com/Icinga/icingadb-web/assets/6977434/7d659ed6-7ee1-4bff-b2dd-95a10332e0e6)

**Comment by nilmerg** [comment]
Pragmatic, as always :joy:
