### ISSUE TITLE
Visualize that a check is currently running

### ISSUE THREAD

**Issue by dwt** [Icinga/icingadb-web#493]
## Is your feature request related to a problem? Please describe.
It is hard to see wether a check is currently running, and how long it took. While this information is available in the 'Source' tab, it is quite hard to see and I am not even sure if I can reliably see wether a check is currently running.

This leads to me launching unnecessary checks even before the last one finished. I encounter this especially if the checks time out (because of some issue I haven't yet determined).

## Describe the solution you'd like
I would like the check visualization to show that a check is currently executing and how long it took.
<img width="551" alt="Bildschirmfoto 2022-02-14 um 10 39 27" src="https://user-images.githubusercontent.com/57199/153839282-6a9b2f2d-33cf-4428-a022-a18ed5f3bff0.png">

I am envisioning showing not a point at the beginning for the last check but a range that shows how long it took to execute that check, as well as a different visualization while the check is executing.

## Describe alternatives you've considered
Looking at the Source tab gives me almost all this information but in a really inconvenient to quickly grasp way.

**Comment by nilmerg** [comment]
Quick draft as I imagine it. Solves two purposes: a) the line visualized the execution time b) the bubble shows when the check ended. It always shows the "last" check information. While the now bubble and point is on the line, the check is presumably still running. Presumably because we can't know this for sure, only by checking if `now < next_check + execution_time`.

<img width="551" alt="153839282-6a9b2f2d-33cf-4428-a022-a18ed5f3bff0" src="https://user-images.githubusercontent.com/16668527/179716496-431f23fa-ab3c-40d8-ae76-050d41fe2249.png">

**Comment by dwt** [comment]
I like that. I would also consider removing the last check result while a check is running. I think that would serve several purposes:

1. Prevent a mix of information from last execution and current execution (that would IMO be a break from the current way this display works)
2. Ensure there is no way to confuse last check result with the time it took to accumulate this check result. That way, the last check result label only ever appears once the result is in, and nothing is displayed in the meantime.

I think I thought of a third thing, but can't remember right now. 🤷

**Comment by nilmerg** [comment]
We cannot know for sure if a check is running. Also, in #600 you said you want a timestamp of the last check result. Why should the last check result now be hidden?

1) If there is indeed a mix of information, it's rather caused by the next check and now bubbles. All other either refer to configuration or a statistic from the last run.
2) The time it took to accumulate the result? That's the execution time isn't it? The line. The last check result is naturally at the end of it, hence at the end of the line.

@flourish86 Please add your thoughts.

**Comment by flourish86** [comment]
This would be a mock up of how this could look.

There are basically two different states:

* One, when the check is still running.
* Another, when the Check Result is available and the timer is running until the next check.

The label for “Now” has been removed, since the goal is to have the now indicator animated (similar to how the time in the “Last Update” and “Next Check” bubbles are).

To clarify the label for the check start could be renamed and to avoid confusion the "Last Check Result” should be renamed to something like “*Last* Execution End”.

![Frame 41](https://github.com/Icinga/icingadb-web/assets/6977434/9774751e-4e87-4da8-91b7-3ff245eaae5d)
