### ISSUE TITLE
Additionally order history events by type

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb-web#587]
## Is your feature request related to a problem? Please describe.

At the moment, history events seem to be ordered only by time. For events with the same timestamp, there seems to be no tie-breaker and events show up in some order (probably some implementation-defined ordering from the database).

## Describe the solution you'd like
I suggest additionally ordering events with the same timestamp by type in a way that reflects the typical order of causation. That is state changes should come first (can trigger downtimes, flapping events, acknowledgement removals) and notifications last (as they typically are the result of something that just happened).

**Comment by nilmerg** [comment]
`history.event_type` is defined as `enum('notification', 'state_change', 'downtime_start', 'downtime_end', 'comment_add', 'comment_remove', 'flapping_start', 'flapping_end', 'ack_set', 'ack_clear')`. Since (at least MySQL) orders enum columns by [index association](https://dev.mysql.com/doc/refman/8.0/en/enum.html#enum-sorting) is this the correct order already? The schema also has no compound index for both `event_time` and `event_type` yet.

**Comment by julianbrost** [comment]
> is this the correct order already?

No, I'd want `state_change, [everything else], notification`.

>The schema also has no compound index for both event_time and event_type yet.

True, but also there will be only very few events at the same time for a checkable, so just sorting maybe 5 elements is super cheap (unless surprise database behavior and it stops using the index when you add another sort term).

**Comment by nilmerg** [comment]
> unless surprise database behavior and it stops using the index when you add another sort term

That's what I'm afraid of.
