### ISSUE TITLE
Uncaught TypeError: array_diff_key(): Argument #1 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingadb-web#606]
## Describe the bug

Clicking on the `Source` tab of any service or host produces the following result.

<img width="1239" alt="Bildschirmfoto 2022-07-26 um 15 56 04" src="https://user-images.githubusercontent.com/57616252/181023652-03f0edb9-a35a-4c4a-946d-33126ea46d85.png">

**Comment by nilmerg** [comment]
Interesting. That should be handled right [here](https://github.com/Icinga/icingadb-web/blob/master/library/Icingadb/Common/ObjectInspectionDetail.php#L119). Though, that `hGet` call seems to return `null` instead of `false` now if there's nothing found. When working on this, it should be ensured that not all other usages of the predis client are outdated as well.
