### ISSUE TITLE
Outputfilter does not work, if check state did not change, but Output did.

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icingadb-web#741]
## Describe the bug
If the output of a check changed, but the state did not, the output is not written to the SQL backend and therefore not available for the filter.
This is rather irritating (and also functionally problematic).

**Comment by nilmerg** [comment]
Yeah, that's a known limitation, but Web can't do anything about it. The only solution would be to filter the results after retrieval from the database, but then this may lead to an empty page. (in the worst case)

And what's more irritating, a filter that doesn't work or just empty pages from 1 to 200 or maybe even only every second page?

**Background:**

If we find results in the database and they'll span over 200 pages, we fetch only a single page. For this page of results, we fetch states from Redis and update the results. To make the filter work, we would need to filter these, say 25, results. This may lead to the case that the page is empty after that because none of the 25 entries matched the filter. We could of course fetch more entries from the database to fill the page up again to 25 results, but then the pagination (limit + offset) on database level is off and broken.

**Comment by ggzengel** [comment]
> ref/NC/836301

What does it mean?
