### ISSUE TITLE
Soft_state=99 wrong color for the icon

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#861]
## Describe the bug
if i get the list icingaweb2/icingadb/services?service.state.soft_state=99 
there are also objects whose the soft_state is at 0 and the icon is green.

## To Reproduce
Rrequest the list for the objects with soft_state 99 but which is still in the unkown status.

## Expected behavior
That all icons are in blue as provided for the status 99

## Screenshots

![soft_state_99](https://github.com/Icinga/icingadb-web/assets/29303758/82d37831-8c29-46ca-893e-ce8d9bd83b33)

# Status 
Status of the object before and after the check manualy.

**Before I check**

```
last_state	unknown
last_state_type	0
severity	0
soft_state	0
state_type	1

```

**After I check**

```
last_state	ok
last_state_type	1
severity	0
soft_state	0
state_type	1

```

## Your Environment
Based on the last snapshot for centos 7.

regards,
Geert

**Comment by yhabteab** [comment]
Hii @gbin2265, this is due to the different states of the database and Redis. If your IcingaDB is running, this should be gone after a few seconds/milliseconds. If you encounter this behavior again, you can verify the last check result/state of that object by navigating to `Host/Service` -> `Source` tab and `Volatile State Details` section.
